import { createFilesApp } from "../apps/files.js";
import { createStoreApp } from "../apps/lucid-store.js";
import { createMediaApp } from "../apps/media.js";
import { createLucidPaint } from "../apps/lucid-paint.js";
import { createCalculator } from "../apps/calculator.js";
import { createNotes } from "../apps/notes.js";
import { createCalendar } from "../apps/calendar.js";
import { createTextEditor } from "../apps/text-editor.js";
import { createTerminal } from "../apps/terminal.js";
import { loadFileSystem } from "./filesystem.js";
import { loadSettings } from "./settings.js";
import { createSettingsApp } from "../apps/settings.js";
import { createBrowser } from "../apps/browser.js";
import { getLucidLevel } from "./lucid-state.js";
import { initializeAppRegistry, getInstalledApps, registerAppLauncher, getAppLauncher } from "./app-registry.js";
import { createLucidStudio } from "../apps/lucid-studio.js";
console.log("Lucid level:", getLucidLevel());
await loadFileSystem();
initializeAppRegistry();
registerAppLauncher("lucid-studio", createLucidStudio);
registerAppLauncher("files", createFilesApp);
registerAppLauncher("settings", createSettingsApp);
registerAppLauncher("terminal", createTerminal);
registerAppLauncher("store", createStoreApp);
registerAppLauncher("calculator", createCalculator);
registerAppLauncher("media", createMediaApp);
registerAppLauncher("paint", createLucidPaint);
registerAppLauncher("notes", createNotes);
registerAppLauncher("calendar", createCalendar);
registerAppLauncher("text-editor", createTextEditor);
registerAppLauncher("browser", createBrowser);
function updateClock() {
    const clock = document.getElementById("clock");
    if (!clock) return;
    const now = new Date();
    const hours = String(now.getHours()).padStart(2, "0");
    const minutes = String(now.getMinutes()).padStart(2, "0");
    const text = `${hours}:${minutes}`;
    if (clock.textContent !== text) clock.textContent = text;
}
updateClock();
setInterval(updateClock, 1000);
