alter table public.lucid_app_submissions add column if not exists storage_provider text not null default 'b2';
alter table public.lucid_app_submissions add column if not exists source_key text;
alter table public.lucid_app_submissions add column if not exists package_size bigint;
alter table public.lucid_apps add column if not exists source_key text;
alter table public.lucid_apps add column if not exists package_size bigint;
alter table public.lucid_apps add column if not exists published_at timestamptz;
alter table public.lucid_app_versions add column if not exists package_size bigint;
alter table public.lucid_developers add column if not exists plan text not null default 'free';
alter table public.lucid_developers add column if not exists plan_expires_at timestamptz;
alter table public.lucid_developers add column if not exists billing_customer_id text;
alter table public.lucid_developers add column if not exists billing_subscription_id text;
create table if not exists public.lucid_app_reviews (id uuid primary key default gen_random_uuid(),app_id text not null references public.lucid_apps(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,rating smallint not null check (rating between 1 and 5),review text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(app_id,user_id));
create table if not exists public.lucid_app_downloads (id uuid primary key default gen_random_uuid(),app_id text not null references public.lucid_apps(id) on delete cascade,user_id uuid references auth.users(id) on delete set null,version text,created_at timestamptz not null default now());
create index if not exists lucid_app_reviews_app_id_idx on public.lucid_app_reviews(app_id);
create index if not exists lucid_app_downloads_app_id_idx on public.lucid_app_downloads(app_id);
create index if not exists lucid_app_submissions_status_idx on public.lucid_app_submissions(status);
create or replace view public.lucid_app_store_stats with (security_invoker=true) as select a.id as app_id,count(distinct r.id)::bigint as review_count,coalesce(round(avg(r.rating)::numeric,2),0)::numeric as average_rating,count(distinct d.id)::bigint as download_count from public.lucid_apps a left join public.lucid_app_reviews r on r.app_id=a.id left join public.lucid_app_downloads d on d.app_id=a.id group by a.id;
alter table public.lucid_developers enable row level security;
alter table public.lucid_app_reviews enable row level security;
alter table public.lucid_app_downloads enable row level security;
drop policy if exists developers_select_own on public.lucid_developers;
drop policy if exists developers_update_own on public.lucid_developers;
create policy developers_select_own on public.lucid_developers for select to authenticated using (id = auth.uid());
create policy developers_update_own on public.lucid_developers for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
drop policy if exists reviews_public_read on public.lucid_app_reviews;
drop policy if exists reviews_insert_own on public.lucid_app_reviews;
drop policy if exists reviews_update_own on public.lucid_app_reviews;
drop policy if exists reviews_delete_own on public.lucid_app_reviews;
create policy reviews_public_read on public.lucid_app_reviews for select to anon,authenticated using (true);
create policy reviews_insert_own on public.lucid_app_reviews for insert to authenticated with check (user_id = auth.uid());
create policy reviews_update_own on public.lucid_app_reviews for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy reviews_delete_own on public.lucid_app_reviews for delete to authenticated using (user_id = auth.uid());
drop policy if exists downloads_insert on public.lucid_app_downloads;
drop policy if exists downloads_read_own on public.lucid_app_downloads;
create policy downloads_insert on public.lucid_app_downloads for insert to anon,authenticated with check (user_id is null or user_id = auth.uid());
create policy downloads_read_own on public.lucid_app_downloads for select to authenticated using (user_id = auth.uid());
revoke all on function public.handle_new_lucid_developer() from anon,authenticated;